### ISSUE TITLE
Export xlsx, Import xls

### ISSUE THREAD

**Issue by LuisMuro** [OCA/role-policy#15]
Hello,

The export_xls() function exports the roles with an ".xlsx" extension but is not possible import roles in xlsx format, to import roles is neccesary enter to file and save as xls.

**Comment by luc-demeyer** [comment]
@LuisMuro 
I'll need more detail to reproduce this issue.
We use xlsx import & export all the time hence the issue will be more specific. Code page related, e.g. special spanish characters ?
If you can attach an xlsx file that fails for the import than we can hopefully reproduce and fix the issue.

**Comment by LuisMuro** [comment]
Hello, i apologise for the delay. To reproduce it, create a new role or open any current role then export it using the export button (export_xls) and save it. Now create a new one, put the name and code of te role and try to import the exported file using Import button (import_policy). Whe you try to import the role an error occurs with the next message:

raise XLRDError(FILE_FORMAT_DESCRIPTIONS[file_format]+'; not supported')
xlrd.biffh.XLRDError: Excel xlsx file; not supported

This is becuase the exported file is saved with ".xlsx" format and this is not supported by the import function.

**Comment by luc-demeyer** [comment]
@LuisMuro 
as said before : we are using the xlsx export and import on a daily basis hence the scenario you describe does work. There is probably something different on your system. 
Can you attach such a failing xlsx file so that I can try to reproduce the issue that you experience ?

**Comment by LuisMuro** [comment]
ok, maybe it is something wrong here, i will check it. ¡Thanks for your answer!.
